/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package account_maintainer;

import java.awt.Color;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;

/**
 *
 * @author Welcome
 */
public class Login_Register extends javax.swing.JFrame {

    /**
     * Creates new form Login_Register
     */
    ////// create borders
    Border default_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(204, 204, 204));
    Border red_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.red);
    Border textFile_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red);

    public Login_Register() {
        initComponents();

        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        ///// get from internet
        TimeZone timeZone = TimeZone.getTimeZone("GMT");
        SimpleDateFormat date_format = new SimpleDateFormat("yyyy-MM-dd");
        Date date = new Date();
        timeZone = TimeZone.getTimeZone("Asia/Kolkata");
        date_format.setTimeZone(timeZone);
        String current_date_time = date_format.format(date);
        System.out.println("Asia/Kolkata-" + current_date_time);

        //// get from system
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        LocalDateTime now = LocalDateTime.now();///fetch localDateTime from here
        String presentDateTime = dtf.format(now); /////convert localtime to String with format 
        System.out.println("\n");
        System.out.println("System : " + presentDateTime);
        System.out.println("\n");

        if (current_date_time.equals(presentDateTime)) {
            System.out.println("Same");
        } else {
            System.out.println("Not Same");
            JOptionPane.showMessageDialog(null, " Correct Your System Date Time!! ", "Error", JOptionPane.ERROR_MESSAGE);
        }

        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        try {
            URL url = new URL("http://www.google.com");
            URLConnection connection = url.openConnection();
            connection.connect();
            System.out.println("Internet is connected");
            jLabel_Checknet.setText("Internet is connected");
            jLabel_Checknet.setForeground(Color.green);
        } catch (MalformedURLException e) {
            System.out.println("Internet is not connected");
            jLabel_Checknet.setText("Internet is not connected..\nUnable to Login..");
            jLabel_Checknet.setForeground(Color.red);
        } catch (IOException e) {
            System.out.println("Internet is not connected");
            jLabel_Checknet.setText("Internet is not connected..\nUnable to Login..");
            jLabel_Checknet.setForeground(Color.red);
        }

        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        //  center form
        this.setLocationRelativeTo(null);

        //  Set borders
        jLabel_Login.setBorder(default_top_border);
        jLabel_Register.setBorder(default_top_border);
//        jTextField_register_username.setBorder(textFile_border);
        jTextField_login_username.setBorder(textFile_border);
        jPasswordField_login_pass.setBorder(textFile_border);

        /////////  Set Icons
        jLabel_login_username.setIcon(new ImageIcon(getClass().getResource("IMAGES/useron.png")));
        jLabel_login_password.setIcon(new ImageIcon(getClass().getResource("IMAGES/lockon.png")));

        //  Call The jLabel mouse click event
        jLabel_LoginMouseClicked(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Container = new javax.swing.JPanel();
        jPanel_main = new javax.swing.JPanel();
        jLabel_Login = new javax.swing.JLabel();
        jLabel_Register = new javax.swing.JLabel();
        jPanel_login = new javax.swing.JPanel();
        jPasswordField_login_pass = new javax.swing.JPasswordField();
        jButton_login = new javax.swing.JButton();
        jLabel_login_username = new javax.swing.JLabel();
        jTextField_login_username = new javax.swing.JTextField();
        jLabel_login_password = new javax.swing.JLabel();
        jLabel_Checknet = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Container.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Login.setBackground(new java.awt.Color(42, 157, 155));
        jLabel_Login.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Login.setText("Login");
        jLabel_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Login.setOpaque(true);
        jLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseClicked(evt);
            }
        });

        jLabel_Register.setBackground(new java.awt.Color(42, 157, 155));
        jLabel_Register.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Register.setText("Register");
        jLabel_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Register.setOpaque(true);
        jLabel_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseClicked(evt);
            }
        });

        jPanel_login.setBackground(new java.awt.Color(255, 255, 255));

        jPasswordField_login_pass.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPasswordField_login_pass.setForeground(new java.awt.Color(153, 153, 153));
        jPasswordField_login_pass.setText("password");
        jPasswordField_login_pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPasswordField_login_passFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField_login_passFocusLost(evt);
            }
        });

        jButton_login.setBackground(new java.awt.Color(0, 153, 204));
        jButton_login.setFont(new java.awt.Font("SansSerif", 2, 26)); // NOI18N
        jButton_login.setForeground(new java.awt.Color(255, 255, 255));
        jButton_login.setText("Login");
        jButton_login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_loginActionPerformed(evt);
            }
        });

        jTextField_login_username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField_login_username.setForeground(new java.awt.Color(153, 153, 153));
        jTextField_login_username.setText("username");
        jTextField_login_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField_login_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField_login_usernameFocusLost(evt);
            }
        });

        jLabel_Checknet.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Checknet.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel_Checknet.setForeground(new java.awt.Color(51, 255, 0));
        jLabel_Checknet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 22)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reissue");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPasswordField_login_pass, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                            .addComponent(jTextField_login_username)))
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel_Checknet, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_loginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton_login, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Checknet, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_login_username, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_login_password, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_login_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jButton_login, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addComponent(jPanel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ContainerLayout = new javax.swing.GroupLayout(jPanel_Container);
        jPanel_Container.setLayout(jPanel_ContainerLayout);
        jPanel_ContainerLayout.setHorizontalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel_ContainerLayout.setVerticalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseClicked

        //  Design the jlabel login onclick
        jLabel_Login.setBorder(red_top_border);
        jLabel_Login.setBackground(Color.white);
        jLabel_Login.setForeground(Color.black);

        //  Design the jlabel register onclick
        jLabel_Register.setBorder(default_top_border);
        jLabel_Register.setBackground(new Color(42, 187, 155));
        jLabel_Register.setForeground(Color.white);

    }//GEN-LAST:event_jLabel_LoginMouseClicked

    private void jLabel_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseClicked

        Register_Frm form = new Register_Frm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        //close the current form (login form)
        this.dispose();

    }//GEN-LAST:event_jLabel_RegisterMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // Close window button
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked


    private void jPasswordField_login_passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_login_passFocusGained

        //clear the password on focus if the text is "password"
        // get the password
        String pass = String.valueOf(jPasswordField_login_pass.getPassword());

        if (pass.trim().toLowerCase().equals("password")) {
            jPasswordField_login_pass.setText("");
            jPasswordField_login_pass.setForeground(new Color(128, 128, 128));
        }

    }//GEN-LAST:event_jPasswordField_login_passFocusGained

    private void jPasswordField_login_passFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField_login_passFocusLost

        // if the text field is equal to password or empty
        // we will set the "username" the in the field
        // on focus lost event
        // get the password
        String pass = String.valueOf(jPasswordField_login_pass.getPassword());

        if (pass.trim().equals("") || jPasswordField_login_pass.getText().trim().toLowerCase().equals("password")) {
            jPasswordField_login_pass.setText("password");
            jPasswordField_login_pass.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_jPasswordField_login_passFocusLost

    private void jTextField_login_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_login_usernameFocusGained

        //clear the textfield on focus if the text is "username"
        if (jTextField_login_username.getText().trim().toLowerCase().equals("username")) {
            jTextField_login_username.setText("");
            jTextField_login_username.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_jTextField_login_usernameFocusGained

    private void jTextField_login_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField_login_usernameFocusLost

        // if the text field is equal to username or empty
        // we will set the "username" the in the field
        // on focus lost event
        if (jTextField_login_username.getText().trim().equals("") || jTextField_login_username.getText().trim().toLowerCase().equals("username")) {
            jTextField_login_username.setText("username");
            jTextField_login_username.setForeground(new Color(153, 153, 153));
        }

    }//GEN-LAST:event_jTextField_login_usernameFocusLost

    private void jButton_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_loginActionPerformed

        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        
        
        
        
        
        //////////////////////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////~~~~~~~~~~~~~~~~~~~~~~////////////////////////////////////
        /////////////////
        ////  check input field is empty or not!!
        /////////////////
        String uname = jTextField_login_username.getText();
        String pass = String.valueOf(jPasswordField_login_pass.getPassword());

        try {

            ////////////////////////////////////////////////////////////////////
            if (uname.isEmpty() || uname.equalsIgnoreCase("username") || pass.isEmpty() || pass.equalsIgnoreCase("password")) {

                JOptionPane.showMessageDialog(null, "Some Field is Empty", "Confirm to Set All Fields", 2);

            } else {

                ////////////////////////////////////////////////////////////////
                ////////////////////////////////////////////////////////////////
                if (!(Pattern.matches("^[a-zA-Z0-9-.]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", uname))) {
                    JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
                } else {

                    //////////////////////////////////////////////////////////////////////////
                    //////////////////////////////////////////////////////////////////////////
                    Connection con;
                    try {

                        ///////////////////////////////
                        ///////////////////////////////
                        ///////////////////////////////
                        try {
                            Class.forName("oracle.jdbc.driver.OracleDriver");
                        } catch (ClassNotFoundException ex) {
                            Logger.getLogger(Register_Frm.class.getName()).log(Level.SEVERE, null, ex);
                        }
                        con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ACCOUNTMAINTAINER", "SWARNAVA");
                        ///////////////////////////////
                        ///////////////////////////////
                        ///////////////////////////////

                        /////////////////////////////////////////////////////////////////////
                        /////////////////////////////////////////////////////////////////////
                        //////////////////////     Fetch System IP Address
                        String sys_ip = "";
                        try {
                            InetAddress localhost = InetAddress.getLocalHost();

                            System.out.println("System IP Address : " + (localhost.getHostAddress()).trim());
                            sys_ip = (localhost.getHostAddress()).trim();
                        } catch (Exception ea) {
                            ea.printStackTrace();
                        }
                        System.out.println(sys_ip);

                        System.out.println(uname + "--" + pass + "--" + sys_ip);

                        PreparedStatement ps = con.prepareStatement("SELECT * FROM USERS WHERE PROP_EMAIL = ? AND PROP_PASS = ?");
                        ps.setString(1, uname);
                        ps.setString(2, pass);
                        // ps.setString(3, sys_ip);
                        int i = ps.executeUpdate();
                        if (i > 0) {

                            ResultSet rs = ps.executeQuery();
                            while (rs.next()) {

                                ///////////////////////////////////////////////////////////////////////
                                ///////////////////////////////////////////////////////////////////////
                                String licncStart = rs.getString("LICENSE_START");
                                String licncEnd = rs.getString("LICENSE_END");

                                ////////////////////
                                ////////////////////
                                ///                 ---------->>>>   seted before
                                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                                LocalDateTime now = LocalDateTime.now();///fetch localDateTime from here
                                //  String presentDateTime = dtf.format(now);/////convert localtime to String with format 
                                ////////////////////
                                ////////////////////

                                LocalDateTime StartDateTime = LocalDateTime.parse(licncStart, dtf);
                                LocalDateTime EndDateTime = LocalDateTime.parse(licncEnd, dtf);

                                if (now.isAfter(StartDateTime) == true && now.isBefore(EndDateTime) == true) {

                                    JOptionPane.showMessageDialog(null, " Login Successfull!! ", "Success", JOptionPane.INFORMATION_MESSAGE);
                                    account_DashBoard form = new account_DashBoard();
                                    form.setVisible(true);
                                    form.pack();
                                    form.setLocationRelativeTo(null);
                                    //close the current form (login form)
                                    this.dispose();

                                } else {
                                    JOptionPane.showMessageDialog(null, " License Date Over!! Reissue Now!! ", "Error", JOptionPane.ERROR_MESSAGE);
                                }
                                ///////////////////////////////////////////////////////////////////////
                                ///////////////////////////////////////////////////////////////////////

                            }

                        } else {
                            JOptionPane.showMessageDialog(null, " User Not Found!! ", "Error", JOptionPane.ERROR_MESSAGE);
                        }

                    } catch (Exception ea) {
                        ea.printStackTrace();
                    }

                    //////////////////////////////////////////////////////////////////////////
                    //////////////////////////////////////////////////////////////////////////
                }

                ////////////////////////////////////////////////////////////////
                ////////////////////////////////////////////////////////////////
            }

            ////////////////////////////////////////////////////////////////////
        } catch (Exception ea) {
            ea.printStackTrace();
        }

        ///////////////////////////////~~~~~~~~~~~~~~~~~~~~~~~/////////////////////////////////////
        ///////////////////////////////////////////////////////////////////////////////////////////
        ///////////////////////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////

    }//GEN-LAST:event_jButton_loginActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        ReIssue_Panel form = new ReIssue_Panel();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        //close the current form (login form)
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton_login;
    private javax.swing.JLabel jLabel_Checknet;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Register;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_login_password;
    private javax.swing.JLabel jLabel_login_username;
    private javax.swing.JPanel jPanel_Container;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JPasswordField jPasswordField_login_pass;
    private javax.swing.JTextField jTextField_login_username;
    // End of variables declaration//GEN-END:variables
}
