/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package account_maintainer;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

import java.io.IOException;
import static java.lang.Thread.sleep;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;

/**
 *
 * @author Welcome
 */
public class Register_Frm extends javax.swing.JFrame {

    
    Border default_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(204, 204, 204));
    Border red_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.red);
    Border textFile_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red);
    
    /**
     * Creates new form Register_Frm
     */
    public Register_Frm() {
        initComponents();
        
        
        
        
        
        
        
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        
        
        
        
        
        
        
        
        
        try {
            URL url = new URL("http://www.google.com");
            URLConnection connection = url.openConnection();
            connection.connect();
            System.out.println("Internet is connected");
            JOptionPane.showMessageDialog(null, " Internet is connected!! ", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (MalformedURLException e) {
            System.out.println("Internet is not connected");
            JOptionPane.showMessageDialog(null, " Internet is not connected!! Unable to Register!! ", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (IOException e) {
            System.out.println("Internet is not connected");
            JOptionPane.showMessageDialog(null, " Internet is not connected!! Unable to Register!! ", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
        
        
        
        
        
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        //  center form
        this.setLocationRelativeTo(null);

        //  Set borders
        jLabel_Login.setBorder(default_top_border);
        jLabel_Register.setBorder(default_top_border);
        
        
        jTextField_register_uname.setBorder(textFile_border);
        
        jTextField_register_phno.setBorder(textFile_border);
        jTextField_register_email.setBorder(textFile_border);
        jTextField_register_shopname.setBorder(textFile_border);
        jTextField_register_shopaddr.setBorder(textFile_border);
        jTextField_register_shopGstin.setBorder(textFile_border);
        
        jPasswordField_oriPass.setBorder(textFile_border);
        jPasswordField_passCheck.setBorder(textFile_border);
        jTextField_licenseKey.setBorder(textFile_border);
        
        
        jLabel_login_uname.setIcon(new ImageIcon(getClass().getResource("IMAGES/useron.png")));
        jLabel_register_password.setIcon(new ImageIcon(getClass().getResource("IMAGES/lockon.png")));
        jLabel_register_check.setIcon(new ImageIcon(getClass().getResource("IMAGES/check.png")));
        jLabel_register_key.setIcon(new ImageIcon(getClass().getResource("IMAGES/key.png")));
        
        jLabel_login_phno.setIcon(new ImageIcon(getClass().getResource("IMAGES/phone.png")));
        jLabel_login_email.setIcon(new ImageIcon(getClass().getResource("IMAGES/email.png")));
        jLabel_login_shopname.setIcon(new ImageIcon(getClass().getResource("IMAGES/GSTIN.png")));
        
        

        //  Call The jLabel mouse click event
        jLabel_RegisterMouseClicked(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_login_username = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel_close = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel_Login = new javax.swing.JLabel();
        jLabel_Register = new javax.swing.JLabel();
        jLabel_login_uname = new javax.swing.JLabel();
        jLabel_register_check = new javax.swing.JLabel();
        jLabel_register_password = new javax.swing.JLabel();
        jLabel_register_key = new javax.swing.JLabel();
        jTextField_register_uname = new javax.swing.JTextField();
        jPasswordField_oriPass = new javax.swing.JPasswordField();
        jPasswordField_passCheck = new javax.swing.JPasswordField();
        jTextField_licenseKey = new javax.swing.JTextField();
        jButton_register_btn = new javax.swing.JButton();
        jLabel_login_phno = new javax.swing.JLabel();
        jTextField_register_phno = new javax.swing.JTextField();
        jLabel_login_email = new javax.swing.JLabel();
        jTextField_register_email = new javax.swing.JTextField();
        jLabel_login_shopname = new javax.swing.JLabel();
        jTextField_register_shopname = new javax.swing.JTextField();
        jTextField_register_shopaddr = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_register_shopGstin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);

        jLabel_close.setBackground(new java.awt.Color(128, 128, 128));
        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(102, 102, 102));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Login.setBackground(new java.awt.Color(42, 157, 155));
        jLabel_Login.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Login.setText("Login");
        jLabel_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Login.setOpaque(true);
        jLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseClicked(evt);
            }
        });

        jLabel_Register.setBackground(new java.awt.Color(42, 157, 155));
        jLabel_Register.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Register.setText("Register");
        jLabel_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Register.setOpaque(true);
        jLabel_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseClicked(evt);
            }
        });

        jLabel_login_uname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_register_check.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_register_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel_register_key.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField_register_uname.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField_register_uname.setForeground(new java.awt.Color(166, 166, 166));

        jPasswordField_oriPass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPasswordField_oriPass.setForeground(new java.awt.Color(153, 153, 153));

        jPasswordField_passCheck.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPasswordField_passCheck.setForeground(new java.awt.Color(153, 153, 153));

        jTextField_licenseKey.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jTextField_licenseKey.setForeground(new java.awt.Color(0, 153, 255));

        jButton_register_btn.setBackground(new java.awt.Color(0, 255, 0));
        jButton_register_btn.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jButton_register_btn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_register_btn.setText("Register");
        jButton_register_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_register_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_register_btnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton_register_btnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton_register_btnMouseExited(evt);
            }
        });
        jButton_register_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_register_btnActionPerformed(evt);
            }
        });

        jLabel_login_phno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField_register_phno.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField_register_phno.setForeground(new java.awt.Color(166, 166, 166));
        jTextField_register_phno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField_register_phnoKeyPressed(evt);
            }
        });

        jLabel_login_email.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField_register_email.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField_register_email.setForeground(new java.awt.Color(166, 166, 166));

        jLabel_login_shopname.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jTextField_register_shopname.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField_register_shopname.setForeground(new java.awt.Color(166, 166, 166));

        jTextField_register_shopaddr.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField_register_shopaddr.setForeground(new java.awt.Color(166, 166, 166));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Shop Address");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("GSTIN No.");

        jTextField_register_shopGstin.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jTextField_register_shopGstin.setForeground(new java.awt.Color(166, 166, 166));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_login_uname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_login_phno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_login_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_login_shopname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_register_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_register_shopname, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_register_shopaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_register_email, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_register_phno, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jLabel_register_password, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_register_check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_register_key, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPasswordField_oriPass, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_register_shopGstin, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField_passCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_licenseKey, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jButton_register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_login_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_uname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_login_phno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_phno, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_login_email, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_email, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_login_shopname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_shopname, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_shopaddr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_register_shopGstin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_register_password, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_oriPass, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_register_check, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_passCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_register_key, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_licenseKey, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_register_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_close)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        
        // Close window button
        this.dispose();
        
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseClicked

        Login_Register form = new Login_Register();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        //close the current form (login form)
        this.dispose();
        
    }//GEN-LAST:event_jLabel_LoginMouseClicked

    private void jLabel_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseClicked

        
        //  Design the jlabel login onclick
        jLabel_Register.setBorder(red_top_border);
        jLabel_Register.setBackground(Color.white);
        jLabel_Register.setForeground(Color.black);

        //  Design the jlabel register onclick
        jLabel_Login.setBorder(default_top_border);
        jLabel_Login.setBackground(new Color(42, 187, 155));
        jLabel_Login.setForeground(Color.white);
        
    }//GEN-LAST:event_jLabel_RegisterMouseClicked

    private void jButton_register_btnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_register_btnMouseEntered
        
        jButton_register_btn.setBackground(new Color(0, 204, 0));
        
    }//GEN-LAST:event_jButton_register_btnMouseEntered

    private void jButton_register_btnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_register_btnMouseExited
        
        jButton_register_btn.setBackground(new Color(0, 255, 0));
        
    }//GEN-LAST:event_jButton_register_btnMouseExited

    private void jButton_register_btnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_register_btnMouseClicked

    }//GEN-LAST:event_jButton_register_btnMouseClicked

    private void jButton_register_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_register_btnActionPerformed
        
        
        /////   check System already register or not!!!
        CheckUser();
        
        
        //////////////////// get All Value
        String uname = jTextField_register_uname.getText();
        String uPhno = jTextField_register_phno.getText();
        String uMail = jTextField_register_email.getText();
        String uShopNm = jTextField_register_shopname.getText();
        String uShopAddr = jTextField_register_shopaddr.getText();
        String ugstin = jTextField_register_shopGstin.getText();
        
        String pass1 = String.valueOf(jPasswordField_oriPass.getPassword());
        String pass2 = String.valueOf(jPasswordField_passCheck.getPassword());
        
        String licnceKey = jTextField_licenseKey.getText();
        
        //////////////////////////////////////////////////////////////////////
        
        if(
            uname.equals(" ") || uname.equals("") || uname.equals(null) ||
            uPhno.equals(" ") || uPhno.equals("") || uPhno.equals(null) ||
            uMail.equals(" ") || uMail.equals("") || uMail.equals(null) ||
            uShopNm.equals(" ") || uShopNm.equals("") || uShopNm.equals(null) ||
            uShopAddr.equals(" ") || uShopAddr.equals("") || uShopAddr.equals(null) ||
            ugstin.equals(" ") || ugstin.equals("") || ugstin.equals(null) ||
            pass1.equals(" ") || pass1.equals("") || pass1.equals(null) ||
            pass2.equals(" ") || pass2.equals("") || pass2.equals(null) ||
            licnceKey.equals(" ") || licnceKey.equals("") || licnceKey.equals(null)
                ){
            
            JOptionPane.showMessageDialog(null, "Some Field is Empty", "Confirm to Set All Fields", 2);
            
        }
        else{
            
            if(pass1.equalsIgnoreCase(pass2)){

                /////////////////////////////////////////////////////////////////////
                //////////////////////     Fetch System IP Address
                String sys_ip = "";
                try{
                    InetAddress localhost = InetAddress.getLocalHost();
                    
                    System.out.println("System IP Address : " + (localhost.getHostAddress()).trim());
                    sys_ip = (localhost.getHostAddress()).trim();
                }catch(Exception ea){
                    ea.printStackTrace();
                }
                System.out.println(sys_ip);
                /////////////////////////////////////////////////////////////////////
                
                
                
                /////// varify email address
                //  if (!(Pattern.matches("^[a-zA-Z0-9]+[@]+[a-zA-Z0-9]+[.]+[a-zA-Z0-9]+$", uMail)))
                if (!(Pattern.matches("^[a-zA-Z0-9-.]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", uMail)))
                {
                    JOptionPane.showMessageDialog(null, "Please enter a valid email", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else
                {
                    //  JOptionPane.showMessageDialog(null, "The email is valid", "Good!", JOptionPane.INFORMATION_MESSAGE);
                    ////////////////////////////////////////////////////////////////////////////
                    
                        Connection con;
                        try{
                            ///////////////////////////////
                            ///////////////////////////////
                            ///////////////////////////////
                            try {
                                Class.forName("oracle.jdbc.driver.OracleDriver");
                            } catch (ClassNotFoundException ex) {
                                Logger.getLogger(Register_Frm.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ACCOUNTMAINTAINER", "SWARNAVA");
                            ///////////////////////////////
                            ///////////////////////////////
                            ///////////////////////////////

                            PreparedStatement ps = con.prepareStatement("SELECT * FROM ISSUE_TBL WHERE KEYID = ?");
                            ps.setString(1, licnceKey);
                            int i = ps.executeUpdate();
                            if(i > 0){
                                
                                //////////////////////////////////////////////////////////////////////
                                //  JOptionPane.showMessageDialog(null, "Present", "Key", 2);
                                
                                ///////////////   check key is already used or not!!
                                PreparedStatement isUsed = con.prepareStatement("SELECT * FROM USERD_KEY WHERE KEYID = ?");
                                isUsed.setString(1, licnceKey);
                                int iu = isUsed.executeUpdate();
                                
                                if(iu > 0){
                                    JOptionPane.showMessageDialog(null, " Already Used!! ", "Key", 2);
                                }else{
                                    
                                    //////////////////////////////////////////////////////////////////////////////
                                    //////////////////  key is valid and not used
                                    
                                    

                                            String presentDateTime = null, EngingDateTime = null;

                                            ResultSet rs = ps.executeQuery();
                                            while(rs.next()){

                                                String duratn = rs.getString("DURATN");

                                                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                                                LocalDateTime now = LocalDateTime.now();///fetch localDateTime from here
                                                presentDateTime = dtf.format(now);/////convert localtime to String with format 

                                                LocalDateTime endTm = LocalDateTime.now();

                                                ///////////////////////////////////////////////////////////////////
                                                if(duratn.equalsIgnoreCase("6 MONTHS")){
                                                    endTm = now.plusMonths(6);
                                                }else if(duratn.equalsIgnoreCase("12 MONTHS")){
                                                    endTm = now.plusYears(1);
                                                }else{

                                                }
                                                ///////////////////////////////////////////////////////////////////

                                                EngingDateTime = dtf.format(endTm);

                                            }


                                                java.util.Random r=new java.util.Random();
                                                int x=r.nextInt(99999);
                                                String RId = "USER-Register-"+x+"IDNO";


                                                PreparedStatement ps1 = con.prepareStatement("INSERT INTO USERS(REGISTERID, PROP_NAME,  PROP_PHNO, PROP_EMAIL, SHOPNAME, SHOP_ADDR, PROP_GST, PROP_PASS, LICENSE_START, LICENSE_END, IP_SYSTEM) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");
                                                ps1.setString(1, RId);
                                                ps1.setString(2, uname);
                                                ps1.setString(3, uPhno);
                                                ps1.setString(4, uMail);
                                                ps1.setString(5, uShopNm);
                                                ps1.setString(6, uShopAddr);
                                                ps1.setString(7, ugstin);
                                                ps1.setString(8, pass1);
                                                ps1.setString(9, presentDateTime);
                                                ps1.setString(10, EngingDateTime);
                                                ps1.setString(11, sys_ip);

                                                int ijk = ps1.executeUpdate();


                                                PreparedStatement ps2 = con.prepareStatement("INSERT INTO USERD_KEY(DATETODAY, KEYID) VALUES(?, ?)");
                                                ps2.setString(1, presentDateTime);
                                                ps2.setString(2, licnceKey);

                                                int ikj = ps2.executeUpdate();

                                                if(ijk > 0 && ikj > 0){
                                                    JOptionPane.showMessageDialog(null, " Registration Successfull!! ", "Status", 2);
                                                    
                                                    //////////////////////
                                                    ////   set all field is null
                                                    
                                                    jTextField_register_uname.setText("");
                                                    jTextField_register_phno.setText("");
                                                    jTextField_register_email.setText("");
                                                    jTextField_register_shopname.setText("");
                                                    jTextField_register_shopaddr.setText("");
                                                    jTextField_register_shopGstin.setText("");
                                                    jPasswordField_oriPass.setText("");
                                                    jPasswordField_passCheck.setText("");
                                                    jTextField_licenseKey.setText("");
                                                    
                                                    //////////////////////
                                                    //////////////////////
                                                    
                                                }else{
                                                    JOptionPane.showMessageDialog(null, " Error Occurred!! ", "Error", JOptionPane.ERROR_MESSAGE);
                                                }
                                    
                                    
                                    //////////////////////////////////////////////////////////////////////////////
                                    //////////////////////////////////////////////////////////////////////////////
                                    
                                }
                                
                                //////////////////////////////////////////////////////////////////////

                            }else{
                                JOptionPane.showMessageDialog(null, "Invalid", "Key", 2);
                            }

                            //////////////////////////////////////////////////////////////////////////////////
                            //////////////////////////////////////////////////////////////////////////////////
                        }
                        catch(Exception ea){
                            ea.printStackTrace();
                        }
                    
                    ////////////////////////////////////////////////////////////////////////////
                }
                
                /////////////////////////////////////////////////////////////////////

            } else {
                JOptionPane.showMessageDialog(null, "Password Does Not Math", "Confirm Password", 2);
            }
            
        }
        
        
        //////////////////////////////////////////////////////////////////////
    }//GEN-LAST:event_jButton_register_btnActionPerformed

    private void jTextField_register_phnoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_register_phnoKeyPressed
        // Allow Only Numeric
//        char c = evt.getKeyChar();
//        if(Character.isLetter(c)){
//            //////////////////// make phone number field disable
//            jTextField_register_phno.setEditable(false);
//        }else{
//            //////////////////// make phone number field normal
//            jTextField_register_phno.setEditable(true);
//        }
        
        

        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode()  == KeyEvent.VK_BACK_SPACE) {
            jTextField_register_phno.setEditable(true);
        } else {
            jTextField_register_phno.setEditable(false);
        }
        
        
    }//GEN-LAST:event_jTextField_register_phnoKeyPressed

    
    
    
    
    
    
    
    
    
    
    
    
    public void CheckUser(){
        
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        
        
        //////////////////////////////////////////////////////////////////////////
        //////////////////////////////////////////////////////////////////////////
        Connection con;
        try {

            ///////////////////////////////
            ///////////////////////////////
            ///////////////////////////////
            try {
                Class.forName("oracle.jdbc.driver.OracleDriver");
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Register_Frm.class.getName()).log(Level.SEVERE, null, ex);
            }
            con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ACCOUNTMAINTAINER", "SWARNAVA");
            ///////////////////////////////
            ///////////////////////////////
            ///////////////////////////////
            
            
            PreparedStatement ps = con.prepareStatement("SELECT * FROM USERS");
            int i = ps.executeUpdate();
            if( i > 0 ){
                ///////////////////////////////////////////
                ///////////////////////////////////////////
                
                sleep(1000);
                
                Login_Register form = new Login_Register();
                form.setVisible(true);
                form.pack();
                form.setLocationRelativeTo(null);
                //close the current form (login form)
                this.dispose();
                ////////////////////////////////////////////
            }
            
            
            
            
            ///////////////////////////////
            ///////////////////////////////
            ///////////////////////////////
            con.close();
        }
        catch(Exception ea){
            ea.printStackTrace();
        }
        
        
        ////////////////////////////////////////////////////////////////////////
        ////////////////////////////////////////////////////////////////////////
        
    }
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Frm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Frm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_register_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Register;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_login_email;
    private javax.swing.JLabel jLabel_login_phno;
    private javax.swing.JLabel jLabel_login_shopname;
    private javax.swing.JLabel jLabel_login_uname;
    private javax.swing.JLabel jLabel_login_username;
    private javax.swing.JLabel jLabel_register_check;
    private javax.swing.JLabel jLabel_register_key;
    private javax.swing.JLabel jLabel_register_password;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField_oriPass;
    private javax.swing.JPasswordField jPasswordField_passCheck;
    private javax.swing.JTextField jTextField_licenseKey;
    private javax.swing.JTextField jTextField_register_email;
    private javax.swing.JTextField jTextField_register_phno;
    private javax.swing.JTextField jTextField_register_shopGstin;
    private javax.swing.JTextField jTextField_register_shopaddr;
    private javax.swing.JTextField jTextField_register_shopname;
    private javax.swing.JTextField jTextField_register_uname;
    // End of variables declaration//GEN-END:variables
}
