/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package account_maintainer;

import java.awt.Color;
import java.net.InetAddress;
import java.net.NetworkInterface;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLConnection;

/**
 *
 * @author Welcome
 */
public class ReIssue_Panel extends javax.swing.JFrame {

    /**
     * Creates new form Login_Register
     */
    ////// create borders
    Border default_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, new Color(204, 204, 204));
    Border red_top_border = BorderFactory.createMatteBorder(2, 0, 0, 0, Color.red);
    Border textFile_border = BorderFactory.createMatteBorder(0, 0, 2, 0, Color.red);

    public ReIssue_Panel() {
        
        initComponents();
        
        //  center form
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Container = new javax.swing.JPanel();
        jPanel_main = new javax.swing.JPanel();
        jLabel_Login = new javax.swing.JLabel();
        jLabel_Register = new javax.swing.JLabel();
        jPanel_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField_getIssueID = new javax.swing.JTextField();
        jButton_IssueBtn = new javax.swing.JButton();
        jLabel_close = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Container.setBackground(new java.awt.Color(204, 204, 204));

        jPanel_main.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_Login.setBackground(new java.awt.Color(42, 157, 155));
        jLabel_Login.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Login.setText("Login");
        jLabel_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Login.setOpaque(true);
        jLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseExited(evt);
            }
        });

        jLabel_Register.setBackground(new java.awt.Color(42, 157, 155));
        jLabel_Register.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel_Register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Register.setText("Register");
        jLabel_Register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Register.setOpaque(true);
        jLabel_Register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel_RegisterMouseExited(evt);
            }
        });

        jPanel_login.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 25)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Re-Issue YourSelf");

        jTextField_getIssueID.setBackground(new java.awt.Color(0, 51, 153));
        jTextField_getIssueID.setFont(new java.awt.Font("SimSun-ExtB", 1, 25)); // NOI18N
        jTextField_getIssueID.setForeground(new java.awt.Color(255, 255, 0));

        jButton_IssueBtn.setBackground(new java.awt.Color(51, 255, 0));
        jButton_IssueBtn.setFont(new java.awt.Font("Serif", 1, 26)); // NOI18N
        jButton_IssueBtn.setForeground(new java.awt.Color(255, 255, 255));
        jButton_IssueBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/account_maintainer/IMAGES/key.png"))); // NOI18N
        jButton_IssueBtn.setText("Issue");
        jButton_IssueBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_IssueBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IssueBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_loginLayout = new javax.swing.GroupLayout(jPanel_login);
        jPanel_login.setLayout(jPanel_loginLayout);
        jPanel_loginLayout.setHorizontalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGroup(jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jTextField_getIssueID, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_loginLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jButton_IssueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel_loginLayout.setVerticalGroup(
            jPanel_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_loginLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jTextField_getIssueID, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_IssueBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel_mainLayout = new javax.swing.GroupLayout(jPanel_main);
        jPanel_main.setLayout(jPanel_mainLayout);
        jPanel_mainLayout.setHorizontalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_mainLayout.createSequentialGroup()
                        .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel_Register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_mainLayout.setVerticalGroup(
            jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_mainLayout.createSequentialGroup()
                .addGroup(jPanel_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel_close.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("X");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ContainerLayout = new javax.swing.GroupLayout(jPanel_Container);
        jPanel_Container.setLayout(jPanel_ContainerLayout);
        jPanel_ContainerLayout.setHorizontalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel_ContainerLayout.setVerticalGroup(
            jPanel_ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_main, javax.swing.GroupLayout.PREFERRED_SIZE, 416, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.PREFERRED_SIZE, 497, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseClicked

//        //  Design the jlabel login onclick
//        jLabel_Login.setBorder(red_top_border);
//        jLabel_Login.setBackground(Color.white);
//        jLabel_Login.setForeground(Color.black);
//
//        //  Design the jlabel register onclick
//        jLabel_Register.setBorder(default_top_border);
//        jLabel_Register.setBackground(new Color(42, 187, 155));
//        jLabel_Register.setForeground(Color.white);
        
        
        
        Login_Register form = new Login_Register();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        //close the current form (login form)
        this.dispose();
        
        

    }//GEN-LAST:event_jLabel_LoginMouseClicked

    private void jLabel_RegisterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseClicked

        Register_Frm form = new Register_Frm();
        form.setVisible(true);
        form.pack();
        form.setLocationRelativeTo(null);
        //close the current form (login form)
        this.dispose();

    }//GEN-LAST:event_jLabel_RegisterMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        // Close window button
        this.dispose();
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_LoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseEntered
        
        jLabel_Login.setForeground(new Color(42,157,155));
        jLabel_Login.setBackground(Color.white);
        Border side_border = BorderFactory.createMatteBorder(0, 2, 2, 2, Color.red);
        jLabel_Login.setBorder(side_border);
        
    }//GEN-LAST:event_jLabel_LoginMouseEntered

    private void jLabel_LoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseExited
        
        jLabel_Login.setForeground(Color.white);
        jLabel_Login.setBackground(new Color(42,157,155));
        Border side_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(42,157,155));
        jLabel_Login.setBorder(side_border);
        
    }//GEN-LAST:event_jLabel_LoginMouseExited

    private void jLabel_RegisterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseEntered
        
        jLabel_Register.setForeground(new Color(42,157,155));
        jLabel_Register.setBackground(Color.white);
        Border side_border = BorderFactory.createMatteBorder(0, 2, 2, 2, Color.red);
        jLabel_Register.setBorder(side_border);
        
    }//GEN-LAST:event_jLabel_RegisterMouseEntered

    private void jLabel_RegisterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisterMouseExited
        
        jLabel_Register.setForeground(Color.white);
        jLabel_Register.setBackground(new Color(42,157,155));
        Border side_border = BorderFactory.createMatteBorder(0, 0, 0, 0, new Color(42,157,155));
        jLabel_Register.setBorder(side_border);
        
    }//GEN-LAST:event_jLabel_RegisterMouseExited

    private void jButton_IssueBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IssueBtnActionPerformed
        
        
        String get_IssueID = jTextField_getIssueID.getText();
        
        
        if(get_IssueID.isEmpty()){
            ////////////////////////////////////////////////////////
            JOptionPane.showMessageDialog(this, "Field is Empty!!", "Warning", JOptionPane.WARNING_MESSAGE);
            ////////////////////////////////////////////////////////
        }else{
            ////////////////////////////////////////////////////////
            ////////////////////////////////////////////////////////
            
            /////////////////////////
            /////////////////////////
            Connection con;
            try {
                ///////////////////////////////
                ///////////////////////////////
                ///////////////////////////////
                try {
                    Class.forName("oracle.jdbc.driver.OracleDriver");
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Register_Frm.class.getName()).log(Level.SEVERE, null, ex);
                }
                con = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521:XE", "ACCOUNTMAINTAINER", "SWARNAVA");
                ///////////////////////////////
                ///////////////////////////////
                ///////////////////////////////

                //////////    check the key is valid or not
                PreparedStatement ps = con.prepareStatement("SELECT * FROM ISSUE_TBL WHERE KEYID = ?");
                ps.setString(1, get_IssueID);
                int i = ps.executeUpdate();
                if(i > 0){
                    
                ////////   check the key is already used or not    
                PreparedStatement ps1 = con.prepareStatement("SELECT * FROM USERD_KEY WHERE KEYID = ?");
                ps1.setString(1, get_IssueID);
                int j = ps1.executeUpdate();
                if(j > 0){
                    JOptionPane.showMessageDialog(this, "Key is Already Used!!", "Warning", JOptionPane.WARNING_MESSAGE);
                }else{
                    
                    
                    ///////////////////////////////////////////////////////////
                    ////////////   the key is Okay and Can be used...
                    
                    String duration = "";
                    ////////   get duration of issued key
                    PreparedStatement ps2 = con.prepareStatement("SELECT * FROM ISSUE_TBL WHERE KEYID = ?");
                    ps2.setString(1, get_IssueID);
                    ResultSet rs2 = ps2.executeQuery();
                    while(rs2.next()){
                        duration = rs2.getString("DURATN");
                    }
                    
                    
                    ///////   get present or starting date time
                    DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                    LocalDateTime now = LocalDateTime.now();///fetch localDateTime from here
                    String presentDateTime = dtf.format(now);/////convert localtime to String with format 

                    LocalDateTime endTm = LocalDateTime.now();
                    
                    //////////////////////////////////////////////////////////////////////////
                    
                    if(duration.equalsIgnoreCase("6 MONTHS")){
                        endTm = now.plusMonths(6);
                    }else if(duration.equalsIgnoreCase("12 MONTHS")){
                        endTm = now.plusYears(1);
                    }else{

                    }
                    
                    /////////////   get ending date time
                    String EngingDateTime = dtf.format(endTm);
                    
                    
                    
                    //////////    set data to USERS table
                    PreparedStatement ps3 = con.prepareStatement("UPDATE USERS SET LICENSE_START = ?, LICENSE_END = ?");
                    ps3.setString(1, presentDateTime);
                    ps3.setString(2, EngingDateTime);
                    int k = ps3.executeUpdate();
                    if(k > 0){
                        
                        
                        
                        ///////    set data to used key table
                        PreparedStatement ps4 = con.prepareStatement("INSERT INTO USERD_KEY(DATETODAY, KEYID) VALUES(?, ?)");
                        ps4.setString(1, presentDateTime);
                        ps4.setString(2, get_IssueID);
                        int l = ps4.executeUpdate();
                        
                        
                        if(l > 0){
                            
                            JOptionPane.showMessageDialog(this, "Re-Issued Successfull...", "Success", JOptionPane.INFORMATION_MESSAGE);
                            jTextField_getIssueID.setText("");
                            
                        }
                        else{
                            ////////////////////////////////////////////////////////
                            JOptionPane.showMessageDialog(this, "Error Occurred!! Please Try Again !!22!!", "Error", JOptionPane.ERROR_MESSAGE);
                            ////////////////////////////////////////////////////////
                        }
                        
                        
                    }
                    else{
                        ////////////////////////////////////////////////////////
                        JOptionPane.showMessageDialog(this, "Error Occurred!! Please Try Again !!11!!", "Error", JOptionPane.ERROR_MESSAGE);
                        ////////////////////////////////////////////////////////
                    }
                    
                    
                    
                    
                    
                }
                    
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Invalid Key!!", "Error", JOptionPane.ERROR_MESSAGE);
                }

                ////////////////////////////////
                ////////////////////////////////
                ////////////////////////////////
                con.close();
            }
            catch(Exception ea){
                ea.printStackTrace();
            }
            
            ////////////////////////////////////////////////////////
            ////////////////////////////////////////////////////////
        }
        
        
        
    }//GEN-LAST:event_jButton_IssueBtnActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReIssue_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReIssue_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReIssue_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReIssue_Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReIssue_Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_IssueBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_Register;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JPanel jPanel_Container;
    private javax.swing.JPanel jPanel_login;
    private javax.swing.JPanel jPanel_main;
    private javax.swing.JTextField jTextField_getIssueID;
    // End of variables declaration//GEN-END:variables
}
